### ISSUE TITLE
Permissions error when adding Discord bot to server

### ISSUE THREAD

**Issue by mkodes** [fatfingers23/trackscape-discord-bot#39]
When I try and add the bot to my clans Discord server it pops up with this error.

![image](https://github.com/user-attachments/assets/b5d70521-a531-45d4-b99e-080d618b84c2)

**Comment by fatfingers23** [comment]
Whoops! Sorry about that. That is my fault. I have to add some extra verification since the bot has gotten a bit more popular lately.  Once you get closer to 100 servers joined Discord ask for more verification.

You may try using the direct link if you were going through the app directory before.
https://discord.com/api/oauth2/authorize?client_id=864626697327869952&permissions=2147568704&scope=bot

 I will find some time tonight to take a look and hopefully straighten this out so that it can be properly verified! Thank you for posting the issue, and I'm sorry about that!

**Comment by fatfingers23** [comment]
Sorry about the long wait! It took a while to submit the application and for it to be approved, but you should now be able to add the bot with the above command! Thank you for your patience, and I hope you enjoy it!
