### ISSUE TITLE
TrackScape no longer sending game messages to discord

### ISSUE THREAD

**Issue by tyler2k15** [fatfingers23/trackscape-discord-bot#48]
This has been an issue four about 7 days, but trackscape is no longer sending messages to discord from the game BUT is sending messages from discord to the game.

As a temporary workaround I have implemented another plugin to send messages to discord.

**Comment by fatfingers23** [comment]
Notes for anyone who may read this issue. The issue was resolved in the plugin's Discord chat. If anyone comes across this same issue, in this instance, it was the clan that had changed their name and no longer matched with their verification code. You can reach out via our discord or issues if you have a similar problem, and we can resolve it.
